#!/usr/bin/perl

#1) read html-dynamic-web.html: get head, non-head
#ii) read data, line-by-line
#iii) allow stdout to be new html-dynamic-web.html

use v5.36.0;
no feature "unicode_strings";
use re "/aa";


