#!/usr/bin/perl

#1) read html-dynamic-web.html: get head, non-head
#ii) read data, line-by-line
#iii) allow stdout to be new html-dynamic-web.html

use v5.36.0;
no feature "unicode_strings";
use re "/aa";

my $target_out = "stdout";
if(scalar (@ARGV) == 2 && $ARGV[0] eq "-o") {
  $target_out = $ARGV[1];
  if($target_out eq "-") {
    $target_out = "stdout";
  }
}

open(my ${han}, "<", 
  "data--dynamicgen") or exit 1;
binmode(${han});

my $ayn = "";
{
  local $/;
  $ayn = <$han>;
}
close(${han});
undef ${han};
my @begin =
  split /\012\/\/DATA_START\012/, $ayn;
if(scalar(@begin) != 2){ exit 2; }
my @end =
  split /\012\/\/DATA_AYNDH\012/, 
    $begin[1];
if(scalar(@end) != 2){ exit 3; }

open(my ${hanii}, "<", "data") or exit 4;
binmode(${hanii});
my @stdout = ();

while ( 1 ) {
my $linei = <$hanii>;

if(defined($linei)) {
if($linei !~ /^\s*$/) {
  chomp $linei;
  my @columns = split(/\s+/, $linei, 1 - (-1) - (-1) - (-1));
  if(scalar(@columns) < 3 || scalar(@columns > 4)){ exit 5; }
  if(scalar(@columns) == 3){push(@columns, "");}

  push(@stdout, "[\$(\"" .
$columns[0] .
"\"), \"" .
$columns[1] .
"\", \"" .
$columns[2] .
"\", \"" .
$columns[3] .
"\"],");
}
else { last; }
}
else { last; }
}
close($hanii);undef $hanii;
if($target_out eq "stdout") {
print $begin[0] .
"\012//DATA START\012" .
join("\012", @stdout) .
"\012//DATA AYNDH\012" . 
$end[1];
} else {
  open(my ${haniii}, ">", $target_out) or exit 33;
  binmode(${haniii});
  print ${haniii}
$begin[0] .
"\012//DATA START\012" .
join("\012", @stdout) .
"\012//DATA AYNDH\012" . 
$end[1];
  close(${haniii});
  undef ${haniii};
}
