#!/usr/bin/perl

use v5.36.0;
use re "/aa";
no feature "unicode_strings";

if(scalar(@ARGV) < 2){exit 6;}
my $ARGV = join(" ", @ARGV);

open(my ${han}, "<", "data") or exit 2;

my $ayn = "";
{
 local $/;
 $ayn = <$han>;
}
close(${han});
undef(${han});
defined($ayn) or exit 3;
my @ayn = 
split /\n/, $ayn;
@ayn = grep { $_ !~ /^\s*$/ } @ayn;
my $id = 1;
if(@ayn > 0 && $ayn[$#ayn] =~ /^(i+) /) {
  $id = length($1) + 1;
}
my $szid = "i" x $id;

open(my ${hanii}, ">", "data") or exit 8;
print ${hanii}
  join("\n", @ayn) .
  "\n" . $szid . " " . $ARGV;
close(${hanii});
undef(${hanii});
