#!/usr/bin/perl

use v5.36.0;
no feature "unicode_strings";
use re "/aa";

if(scalar(@ARGV) != 1 && scalar(@ARGV) != 3){ exit 1; }
my $argv = $ARGV[0];
if($argv !~ /\.html$/){ exit 2; }
if(! -f $argv){ exit 6; }

my $target_out = "stdout";
if(scalar(@ARGV) == 3 &&
   $ARGV[1] eq "-o") {
  $target_out = $ARGV[2];
  if($target_out eq "-") {
    $target_out = "stdout";
  }
}


open(my ${han}, "<", $argv) or exit 3;
binmode(${han});
my $ayn = "";
{
  local $/;
  $ayn = <$han>;
}
close(${han});
undef ${han};
defined($ayn) or exit 8;
if($ayn eq "") { exit 10; }

my $sz = $ayn;
my $worked = 0;
while ( 1 ) {
if($sz =~ s/<td>([^<]+)/<td style=""><b>$1<\/b>/) {
  $worked = 1;
  $sz =~ s/<td>/<td style="">/;
  $sz =~ s/<td>([^<]+)/<td style=""><em>$1<\/em>/;
  $sz =~ s/<td>/<td style="">/;
  next;
}
last;
}
if(!$worked){ exit 9; }


if($target_out eq "stdout") {
  print $sz;
} else {
  open(my ${haniii}, ">", $target_out) or exit 33;
  binmode(${haniii});
  print ${haniii} $sz;
  close(${haniii});
  undef ${haniii};
}
