#!/usr/bin/perl

use v5.36.0;
use re "/aa";
no feature "unicode_strings";

if(!@ARGV) {

print "Enter words\012";
print "(name sect dataiii dataiii daataiii)\012";
my ${han} = undef;


while ( 1 ) {

my $ARGV = <STDIN>;
if(!defined($ARGV)){ last; }
chomp($ARGV);
if($ARGV eq "") {
  last;
}
if($ARGV =~ /^\s*$/){ last ; }

my @artest = split / /, $ARGV;
if(scalar(@artest) < 2){ last; }

my $ayn = "";
if( -f "words.log") {
open(${han},
  "<",
  "words.log") 
  or exit 2;
binmode(${han});

{
 local $/;
 $ayn = <$han>;
}
close(${han});
undef(${han});
} #</AYT>

defined($ayn) or exit 3;
my @ayn = 
split /\012/, $ayn;
undef $ayn;
@ayn = grep { $_ !~ /^\s*$/ } @ayn;
my $id = 1;
if(@ayn > 0 && $ayn[$#ayn] =~ /^(i+) /) {
  $id = length($1) + 1;
}
my $szid = "i" x $id;
undef $id;

open(${han}, ">", "words.log") or exit 8;
binmode(${han});
print ${han}
  join("\012", @ayn) .
  ( @ayn ? "\012" : "" ) .
  $szid . " " . $ARGV;
close(${han});
undef(${han});

} #</WHILE>


} #</AYT>
